kind: Service
apiVersion: v1
metadata:
  name: servicio-cliente
spec:
  type: LoadBalancer
  selector:
    app: servicio-cliente
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: servicio-cliente-tracing
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/clientes.*
        backend:
          serviceName: servicio-cliente
          servicePort: 8081
    

